version: "3"
services:
  postgres:
    container_name: cresh_api_postgres
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - cresh_api_postgres
 
  pgadmin:
    links:
    - postgres:cresh_api_postgres
    container_name: cresh_api_pgadmin
    image: dpage/pgadmin4:latest
    ports:
    - "8081:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - cresh_api_postgres
 
networks:
  cresh_api_postgres:
    driver: bridge